/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardTokenRouteImport } from './routes/_dashboard/token'
import { Route as DashboardProvidersRouteImport } from './routes/_dashboard/providers'
import { Route as DashboardAppsIndexRouteImport } from './routes/_dashboard/apps/index'
import { Route as DashboardAppsAppIdRouteImport } from './routes/_dashboard/apps/$appId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTokenRoute = DashboardTokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProvidersRoute = DashboardProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsIndexRoute = DashboardAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsAppIdRoute = DashboardAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/providers': typeof DashboardProvidersRoute
  '/token': typeof DashboardTokenRoute
  '/apps/$appId': typeof DashboardAppsAppIdRoute
  '/apps/': typeof DashboardAppsIndexRoute
}
export interface FileRoutesByTo {
  '/providers': typeof DashboardProvidersRoute
  '/token': typeof DashboardTokenRoute
  '/': typeof DashboardIndexRoute
  '/apps/$appId': typeof DashboardAppsAppIdRoute
  '/apps': typeof DashboardAppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/providers': typeof DashboardProvidersRoute
  '/_dashboard/token': typeof DashboardTokenRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/apps/$appId': typeof DashboardAppsAppIdRoute
  '/_dashboard/apps/': typeof DashboardAppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/providers' | '/token' | '/apps/$appId' | '/apps/'
  fileRoutesByTo: FileRoutesByTo
  to: '/providers' | '/token' | '/' | '/apps/$appId' | '/apps'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/providers'
    | '/_dashboard/token'
    | '/_dashboard/'
    | '/_dashboard/apps/$appId'
    | '/_dashboard/apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/token': {
      id: '/_dashboard/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof DashboardTokenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/providers': {
      id: '/_dashboard/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof DashboardProvidersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/apps/': {
      id: '/_dashboard/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof DashboardAppsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/apps/$appId': {
      id: '/_dashboard/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof DashboardAppsAppIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardProvidersRoute: typeof DashboardProvidersRoute
  DashboardTokenRoute: typeof DashboardTokenRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAppsAppIdRoute: typeof DashboardAppsAppIdRoute
  DashboardAppsIndexRoute: typeof DashboardAppsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProvidersRoute: DashboardProvidersRoute,
  DashboardTokenRoute: DashboardTokenRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAppsAppIdRoute: DashboardAppsAppIdRoute,
  DashboardAppsIndexRoute: DashboardAppsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
