/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardTestRouteImport } from './routes/_dashboard/test'
import { Route as DashboardProvidersRouteImport } from './routes/_dashboard/providers'
import { Route as DashboardAppsIndexRouteImport } from './routes/_dashboard/apps/index'
import { Route as DashboardAppsAppIdRouteImport } from './routes/_dashboard/apps/$appId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestRoute = DashboardTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProvidersRoute = DashboardProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsIndexRoute = DashboardAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsAppIdRoute = DashboardAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/providers': typeof DashboardProvidersRoute
  '/test': typeof DashboardTestRoute
  '/apps/$appId': typeof DashboardAppsAppIdRoute
  '/apps/': typeof DashboardAppsIndexRoute
}
export interface FileRoutesByTo {
  '/providers': typeof DashboardProvidersRoute
  '/test': typeof DashboardTestRoute
  '/': typeof DashboardIndexRoute
  '/apps/$appId': typeof DashboardAppsAppIdRoute
  '/apps': typeof DashboardAppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/providers': typeof DashboardProvidersRoute
  '/_dashboard/test': typeof DashboardTestRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/apps/$appId': typeof DashboardAppsAppIdRoute
  '/_dashboard/apps/': typeof DashboardAppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/providers' | '/test' | '/apps/$appId' | '/apps/'
  fileRoutesByTo: FileRoutesByTo
  to: '/providers' | '/test' | '/' | '/apps/$appId' | '/apps'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/providers'
    | '/_dashboard/test'
    | '/_dashboard/'
    | '/_dashboard/apps/$appId'
    | '/_dashboard/apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/test': {
      id: '/_dashboard/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof DashboardTestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/providers': {
      id: '/_dashboard/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof DashboardProvidersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/apps/': {
      id: '/_dashboard/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof DashboardAppsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/apps/$appId': {
      id: '/_dashboard/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof DashboardAppsAppIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardProvidersRoute: typeof DashboardProvidersRoute
  DashboardTestRoute: typeof DashboardTestRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAppsAppIdRoute: typeof DashboardAppsAppIdRoute
  DashboardAppsIndexRoute: typeof DashboardAppsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProvidersRoute: DashboardProvidersRoute,
  DashboardTestRoute: DashboardTestRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAppsAppIdRoute: DashboardAppsAppIdRoute,
  DashboardAppsIndexRoute: DashboardAppsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
