/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardTokenRouteImport } from './routes/_dashboard/token'
import { Route as DashboardProvidersRouteImport } from './routes/_dashboard/providers'
import { Route as DashboardAppsRouteImport } from './routes/_dashboard/apps'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTokenRoute = DashboardTokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProvidersRoute = DashboardProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsRoute = DashboardAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/apps': typeof DashboardAppsRoute
  '/providers': typeof DashboardProvidersRoute
  '/token': typeof DashboardTokenRoute
}
export interface FileRoutesByTo {
  '/apps': typeof DashboardAppsRoute
  '/providers': typeof DashboardProvidersRoute
  '/token': typeof DashboardTokenRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/apps': typeof DashboardAppsRoute
  '/_dashboard/providers': typeof DashboardProvidersRoute
  '/_dashboard/token': typeof DashboardTokenRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apps' | '/providers' | '/token'
  fileRoutesByTo: FileRoutesByTo
  to: '/apps' | '/providers' | '/token' | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/apps'
    | '/_dashboard/providers'
    | '/_dashboard/token'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/token': {
      id: '/_dashboard/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof DashboardTokenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/providers': {
      id: '/_dashboard/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof DashboardProvidersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/apps': {
      id: '/_dashboard/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof DashboardAppsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAppsRoute: typeof DashboardAppsRoute
  DashboardProvidersRoute: typeof DashboardProvidersRoute
  DashboardTokenRoute: typeof DashboardTokenRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppsRoute: DashboardAppsRoute,
  DashboardProvidersRoute: DashboardProvidersRoute,
  DashboardTokenRoute: DashboardTokenRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
